# Generated by Django 4.2.20 on 2025-05-17 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nome", models.CharField(default="", max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "renda_fixa_bancaria",
                                "Renda Fixa Bancária (CDB, LCI, LCA)",
                            ),
                            ("titulos_publicos", "Títulos Públicos (Tesouro Direto)"),
                            (
                                "debentures_creditos",
                                "Debêntures e Créditos (Debêntures, CRI, CRA)",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("emissor", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "tipo_negociacao",
                    models.CharField(
                        choices=[("bolsa", "Bolsa"), ("balcao", "Balcão")],
                        default="bolsa",
                        max_length=20,
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "taxa_rentabilidade",
                    models.DecimalField(
                        decimal_places=2, help_text="Em percentual (%)", max_digits=5
                    ),
                ),
                (
                    "tipo_juros",
                    models.CharField(
                        choices=[
                            ("prefixado", "Prefixado"),
                            ("posfixado", "Pós-fixado"),
                            ("hibrido", "Híbrido"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_emissao", models.DateField()),
                ("data_vencimento", models.DateField()),
                (
                    "liquidez",
                    models.CharField(
                        choices=[
                            ("diaria", "Diária"),
                            ("apos_vencimento", "Após Vencimento"),
                        ],
                        max_length=50,
                    ),
                ),
                ("isento_impostos", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("resgatado", "Resgatado"),
                            ("vencido", "Vencido"),
                        ],
                        default="ativo",
                        max_length=50,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
