# Generated by Django 4.2.20 on 2025-06-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_rest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ativo",
            name="isento_impostos",
        ),
        migrations.RemoveField(
            model_name="ativo",
            name="status",
        ),
        migrations.AddField(
            model_name="ativo",
            name="incentivo_fiscal",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o ativo tem benefício fiscal (isenção ou desconto em impostos).",
            ),
        ),
        migrations.AddField(
            model_name="ativo",
            name="percentual_desconto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual do benefício fiscal aplicado ao ativo (exemplo: 15 para 15%).",
                max_digits=5,
                null=True,
            ),
        ),
    ]
