# Generated by Django 4.2.20 on 2025-06-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_rest", "0002_remove_ativo_isento_impostos_remove_ativo_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ativo",
            name="taxa_rentabilidade",
        ),
        migrations.AddField(
            model_name="ativo",
            name="indexador",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CDI", "CDI"),
                    ("SELIC", "SELIC"),
                    ("IPCA", "IPCA"),
                    ("IGPM", "IGPM"),
                ],
                help_text="Indexador econômico (CDI, SELIC, IPCA, etc.).",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ativo",
            name="percentual_sobre_indexador",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual sobre o indexador (Ex.: 110% CDI).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ativo",
            name="taxa_fixa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Taxa fixa anual em percentual (%).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ativo",
            name="incentivo_fiscal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ativo",
            name="percentual_desconto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual de desconto fiscal (se aplicável).",
                max_digits=5,
                null=True,
            ),
        ),
    ]
