# Generated by Django 4.2.20 on 2025-06-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_rest", "0003_remove_ativo_taxa_rentabilidade_ativo_indexador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativo",
            name="quantidade",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
