# Generated by Django 4.2.20 on 2025-06-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_rest", "0004_ativo_quantidade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ativo",
            old_name="incentivo_fiscal",
            new_name="possuiImposto",
        ),
        migrations.RemoveField(
            model_name="ativo",
            name="percentual_desconto",
        ),
        migrations.AddField(
            model_name="ativo",
            name="aliquotaImposto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentual de imposto sobre o rendimento (ex: 15 para 15%).",
                max_digits=5,
                null=True,
            ),
        ),
    ]
